name: kickstarter

services:
  kickstarter:
    image: europe-west1-docker.pkg.dev/solar-imprint-456810-d6/kickstarter/kickstarter-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ROOT: /kickstarter
